<p>Given the code below, use the correct method on line 3 in order to find out the number of elements in <strong>my_list</strong>.</p>

In [1]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

char = len(my_list)

print(char)

7

<p>Given the code below, use the correct code on line 3 in order to remove the element of <strong>my_list</strong> located at index 5.</p>

In [4]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_list.remove('Java')

print(my_list)

[10, 10.5, 20, 30, 'Python', 'Ruby']

<p>Given the code below, use the correct method on line 3 in order to add the element <strong>'C++' </strong>at the end of <strong>my_list</strong>.</p>

In [10]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_list.append('C++')

print(my_list)

[10, 10.5, 20, 30, 'Python', 'Java', 'Ruby', 'C++']

<p>Given the code below, use the correct method on line 3 in order to remove the element <strong>30 </strong>from <strong>my_list</strong>.</p>

In [11]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_list.remove(30)

print(my_list)

[10, 10.5, 20, 'Python', 'Java', 'Ruby']

<p>Given the code below, use the correct method on line 3 in order to return the index of the element <strong>10.5 </strong>in <strong>my_list</strong>.</p>

In [12]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

index = my_list.pop(1)

print(index)

10.5

<p>Given the code below, use the correct method on line 3 in order to insert the element <strong>77 </strong>at index 4 in <strong>my_list</strong>.</p>

In [13]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_list.insert(4, 77)

print(my_list)

[10, 10.5, 20, 30, 77, 'Python', 'Java', 'Ruby']

<p>Given the code below, use the correct method on line 3 in order to concatenate <strong>my_list</strong> with <strong>[100, 101, 102]</strong>, by adding the latter at the end of <strong>my_list</strong>.</p>

In [18]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_list_2 = [100, 101, 102]
print(my_list + my_list_2)

[10, 10.5, 20, 30, 'Python', 'Java', 'Ruby', 100, 101, 102]

<p>Given the code below, use the correct method on line 3 in order to find out how many times does the element <strong>20 </strong>occur in <strong>my_list</strong>.</p>

In [20]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

howmany = my_list.count(20)

print(howmany)

1

<p>Given the code below, use the correct function on line 3 in order to sort the elements of <strong>my_list</strong> in ascending order.</p>

In [21]:
my_list = [10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99]

asc = sorted(my_list)

print(asc)

[10, 10.5, 11.01, 19.25, 20, 25.6, 29.99, 30]

<p>Given the code below, use the correct function (and argument) on line 3 in order to sort the elements of <strong>my_list</strong> in descending order.</p>

In [22]:
my_list = [10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99]

asc = sorted(my_list, reverse=True)

print(asc)

[30, 29.99, 25.6, 20, 19.25, 11.01, 10.5, 10]

<p>Given the code below, use the correct function on line 3 in order to find out the smallest number in <strong>my_list</strong>.</p>

In [23]:
my_list = [10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99]

small = sorted(my_list) [0]

print(small)

10

<p>Given the code below, use the correct function on line 3 in order to find out the largest number in <strong>my_list</strong>.</p>

In [27]:
my_list = [10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99]

large = sorted(my_list) [-1]

print(large)

30

<p>Given the code below, use the correct function on line 3 in order to get the sum of all the elements of <strong>my_list</strong>.</p>

In [28]:
my_list = [10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99]

add = sum(my_list)

print(add)

156.35

<p>Given the code below, use the correct method on line 3 in order to delete all the elements from <strong>my_list</strong> and obtain an empty list.</p>

In [31]:
my_list = [10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99]

my_list.clear()
print(my_list)

[]

<p>Given the code below, use the correct operators and parentheses on line 3 in order to add the elements of <strong>[30.01, 30.02, 30.03] </strong>to <strong>my_list</strong> and multiply the resulting list by <strong>2</strong>.</p>

In [32]:
my_list = [10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99]

add = (my_list + [30.01, 30.02, 30.03]) *2

print(add)

[10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99, 30.01, 30.02, 30.03, 10, 10.5, 20, 30, 25.6, 19.25, 11.01, 29.99, 30.01, 30.02, 30.03]

<p>Given the code below, use the correct code on line 3 in order to return the element <strong>20 </strong>from <strong>my_list</strong> based on its index.</p>

In [34]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

element = my_list[2]
print(element)

20

<p>Given the code below, use the correct code on line 3 in order to return the element <strong>Java </strong>from <strong>my_list</strong> based on its index (negative).</p>

In [35]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

element = my_list[-2]

print(element)

Java

<p>Given the code below, use the correct code on line 3 in order to return a slice made of <strong>[30, 'Python', 'Java'] </strong>from <strong>my_list</strong> based on positive indexes.</p>

In [36]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[3:6]

print(my_slice)

[30, 'Python', 'Java']

<p>Given the code below, use the correct code on line 3 in order to return a slice made of <strong>[30, 'Python', 'Java'] </strong>from <strong>my_list</strong> based on negative indexes.</p>

In [44]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[-4:-1]

print(my_slice)

[30, 'Python', 'Java']

<p>Given the code below, use the correct code on line 3 in order to return <strong>my_list</strong> except the first 3 elements, using a single, positive index.</p>

In [45]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[3:]

print(my_slice) #[30, 'Python', 'Java', 'Ruby']

[30, 'Python', 'Java', 'Ruby']

<p>Given the code below, use the correct code on line 3 in order to return <strong>my_list</strong> except the last 4 elements, using a single, negative index.</p>

In [47]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[:-4]

print(my_slice) #[10, 10.5, 20]

[10, 10.5, 20]

<p>Given the code below, use the correct code on line 3 in order to return <strong>my_list</strong> except the first 3 elements, using a single, negative index.</p>

In [48]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[-4:]

print(my_slice) #[30, 'Python', 'Java', 'Ruby']

[30, 'Python', 'Java', 'Ruby']

<p>Given the code below, use the correct code on line 3 in order to return <strong>my_list</strong> except the last 2 elements, using a single, positive index.</p>

In [49]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[:5]

print(my_slice) #[10, 10.5, 20, 30, 'Python']

[10, 10.5, 20, 30, 'Python']

<p>Given the code below, use the correct code on line 3 in order to return every third element of <strong>my_list</strong> starting with the first element of the list.</p>

In [50]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[0::3]

print(my_slice) #[10, 30, 'Ruby']

[10, 30, 'Ruby']

<p>Given the code below, use the correct code on line 3 in order to return every fourth element of <strong>my_list</strong> starting with the last element of the list.</p>

In [55]:
my_list = [10, 10.5, 20, 30, 'Python', 'Java', 'Ruby']

my_slice = my_list[-1::-4]

print(my_slice) #['Ruby', 20]

['Ruby', 20]